{"uuid": "a66d5310-0c87-474a-9ad5-83493894ee40", "children": ["2bf2e895-f3d5-486f-9049-9c0203623d00"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain\n  (Session info: MicrosoftEdge=139.0.3405.111)\nStacktrace:\n\tGetHandleVerifier [0x0x7ff775ca81f5+23461]\n\t(No symbol) [0x0x7ff775bfc2e0]\n\t(No symbol) [0x0x7ff7759cce40]\n\t(No symbol) [0x0x7ff775a6a834]\n\t(No symbol) [0x0x7ff775a3a6ba]\n\t(No symbol) [0x0x7ff775a0f58d]\n\t(No symbol) [0x0x7ff775a5754f]\n\t(No symbol) [0x0x7ff775a3a423]\n\t(No symbol) [0x0x7ff775a0ea86]\n\t(No symbol) [0x0x7ff775a0dd11]\n\t(No symbol) [0x0x7ff775a0e8b3]\n\t(No symbol) [0x0x7ff775b0dd3d]\n\t(No symbol) [0x0x7ff775b1b0c8]\n\tGetHandleVerifier [0x0x7ff775d8803b+940523]\n\tGetHandleVerifier [0x0x7ff775d90d91+976705]\n\t(No symbol) [0x0x7ff775c09ed1]\n\t(No symbol) [0x0x7ff775c028b4]\n\t(No symbol) [0x0x7ff775c02a03]\n\t(No symbol) [0x0x7ff775bf44a6]\n\tBaseThreadInitThunk [0x0x7ffd039e7374+20]\n\tRtlUserThreadStart [0x0x7ffd057bcc91+33]\n\n", "trace": "  File \"d:\\tools\\python 37\\lib\\site-packages\\pluggy\\_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\tools\\python 37\\lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\tools\\python 37\\lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\快沃开放管理平台自动化测试脚本\\管理平台UI\\conftest.py\", line 11, in browser\n    driver = DriverManager.get_driver()#使用我们自定义的驱动管理\n  File \"D:\\快沃开放管理平台自动化测试脚本\\管理平台UI\\utils\\driver_manager.py\", line 27, in get_driver\n    driver.add_cookie(cookie)\n  File \"d:\\tools\\python 37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 634, in add_cookie\n    self.execute(Command.ADD_COOKIE, {\"cookie\": cookie_dict})\n  File \"d:\\tools\\python 37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 345, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\tools\\python 37\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1756352492000, "stop": 1756352493502}], "start": 1756352492000, "stop": 1756352493705}